/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as IndexRouteImport } from './routes/index'
import { Route as MarketerSigninRouteImport } from './routes/marketer.signin'
import { Route as MarketerRegisterRouteImport } from './routes/marketer.register'
import { Route as BusinessSigninRouteImport } from './routes/business.signin'
import { Route as BusinessRegisterRouteImport } from './routes/business.register'
import { Route as LovableEmailQueueProcessRouteImport } from './routes/lovable/email/queue/process'

const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const MarketerSigninRoute = MarketerSigninRouteImport.update({
  id: '/marketer/signin',
  path: '/marketer/signin',
  getParentRoute: () => rootRouteImport,
} as any)
const MarketerRegisterRoute = MarketerRegisterRouteImport.update({
  id: '/marketer/register',
  path: '/marketer/register',
  getParentRoute: () => rootRouteImport,
} as any)
const BusinessSigninRoute = BusinessSigninRouteImport.update({
  id: '/business/signin',
  path: '/business/signin',
  getParentRoute: () => rootRouteImport,
} as any)
const BusinessRegisterRoute = BusinessRegisterRouteImport.update({
  id: '/business/register',
  path: '/business/register',
  getParentRoute: () => rootRouteImport,
} as any)
const LovableEmailQueueProcessRoute =
  LovableEmailQueueProcessRouteImport.update({
    id: '/lovable/email/queue/process',
    path: '/lovable/email/queue/process',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/business/register': typeof BusinessRegisterRoute
  '/business/signin': typeof BusinessSigninRoute
  '/marketer/register': typeof MarketerRegisterRoute
  '/marketer/signin': typeof MarketerSigninRoute
  '/lovable/email/queue/process': typeof LovableEmailQueueProcessRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/business/register': typeof BusinessRegisterRoute
  '/business/signin': typeof BusinessSigninRoute
  '/marketer/register': typeof MarketerRegisterRoute
  '/marketer/signin': typeof MarketerSigninRoute
  '/lovable/email/queue/process': typeof LovableEmailQueueProcessRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/business/register': typeof BusinessRegisterRoute
  '/business/signin': typeof BusinessSigninRoute
  '/marketer/register': typeof MarketerRegisterRoute
  '/marketer/signin': typeof MarketerSigninRoute
  '/lovable/email/queue/process': typeof LovableEmailQueueProcessRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/dashboard'
    | '/business/register'
    | '/business/signin'
    | '/marketer/register'
    | '/marketer/signin'
    | '/lovable/email/queue/process'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/dashboard'
    | '/business/register'
    | '/business/signin'
    | '/marketer/register'
    | '/marketer/signin'
    | '/lovable/email/queue/process'
  id:
    | '__root__'
    | '/'
    | '/dashboard'
    | '/business/register'
    | '/business/signin'
    | '/marketer/register'
    | '/marketer/signin'
    | '/lovable/email/queue/process'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DashboardRoute: typeof DashboardRoute
  BusinessRegisterRoute: typeof BusinessRegisterRoute
  BusinessSigninRoute: typeof BusinessSigninRoute
  MarketerRegisterRoute: typeof MarketerRegisterRoute
  MarketerSigninRoute: typeof MarketerSigninRoute
  LovableEmailQueueProcessRoute: typeof LovableEmailQueueProcessRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/marketer/signin': {
      id: '/marketer/signin'
      path: '/marketer/signin'
      fullPath: '/marketer/signin'
      preLoaderRoute: typeof MarketerSigninRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/marketer/register': {
      id: '/marketer/register'
      path: '/marketer/register'
      fullPath: '/marketer/register'
      preLoaderRoute: typeof MarketerRegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/business/signin': {
      id: '/business/signin'
      path: '/business/signin'
      fullPath: '/business/signin'
      preLoaderRoute: typeof BusinessSigninRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/business/register': {
      id: '/business/register'
      path: '/business/register'
      fullPath: '/business/register'
      preLoaderRoute: typeof BusinessRegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lovable/email/queue/process': {
      id: '/lovable/email/queue/process'
      path: '/lovable/email/queue/process'
      fullPath: '/lovable/email/queue/process'
      preLoaderRoute: typeof LovableEmailQueueProcessRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DashboardRoute: DashboardRoute,
  BusinessRegisterRoute: BusinessRegisterRoute,
  BusinessSigninRoute: BusinessSigninRoute,
  MarketerRegisterRoute: MarketerRegisterRoute,
  MarketerSigninRoute: MarketerSigninRoute,
  LovableEmailQueueProcessRoute: LovableEmailQueueProcessRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
