/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as MarketerSigninRouteImport } from './routes/marketer.signin'
import { Route as MarketerRegisterRouteImport } from './routes/marketer.register'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const MarketerSigninRoute = MarketerSigninRouteImport.update({
  id: '/marketer/signin',
  path: '/marketer/signin',
  getParentRoute: () => rootRouteImport,
} as any)
const MarketerRegisterRoute = MarketerRegisterRouteImport.update({
  id: '/marketer/register',
  path: '/marketer/register',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/marketer/register': typeof MarketerRegisterRoute
  '/marketer/signin': typeof MarketerSigninRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/marketer/register': typeof MarketerRegisterRoute
  '/marketer/signin': typeof MarketerSigninRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/marketer/register': typeof MarketerRegisterRoute
  '/marketer/signin': typeof MarketerSigninRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/marketer/register' | '/marketer/signin'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/marketer/register' | '/marketer/signin'
  id: '__root__' | '/' | '/marketer/register' | '/marketer/signin'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  MarketerRegisterRoute: typeof MarketerRegisterRoute
  MarketerSigninRoute: typeof MarketerSigninRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/marketer/signin': {
      id: '/marketer/signin'
      path: '/marketer/signin'
      fullPath: '/marketer/signin'
      preLoaderRoute: typeof MarketerSigninRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/marketer/register': {
      id: '/marketer/register'
      path: '/marketer/register'
      fullPath: '/marketer/register'
      preLoaderRoute: typeof MarketerRegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  MarketerRegisterRoute: MarketerRegisterRoute,
  MarketerSigninRoute: MarketerSigninRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
